name: Punch In

on:
  schedule:
    - cron: 55 13 * * *
  workflow_dispatch:

jobs:
  punch_in:
    runs-on: ubuntu-20.04
    env:
      ACCOUNTS: ${{ secrets.ACCOUNTS }}
    steps:
      - name: "checkout"
        uses: actions/checkout@v1
      - name: "Punch in"
        run: ./punch_in
      - name: "Run qiandao.py"
        run: |
          python -m pip install --upgrade pip
          pip install requests  # 安装 requests 库
          python jmqiandao.py
